- README.md
- src/constants/tokens.ts
- src/index.ts
- src/quote/zeroEx/componentsQuoteProvider.test.ts
- src/quote/zeroEx/componentsQuoteProvider.ts
- src/quote/zeroEx/index.test.ts
- src/quote/zeroEx/index.ts
* Adds component quotes provider
* Fixes issues with FlashMintZeroEx quotes e.g. when there is only one component and it is equal to the input/output token
* Docs: indicate deprecated tokens
> Add component quotes provider

- src/tests/btc2xFLI.test.ts
- src/tests/iceth.test.ts
- src/utils/UniswapPath.test.ts
- src/utils/swapData.ts
As 0x seemed to have renamed the path from `uniswapPath` to just `path` this caused issues of getting the correct fees for UniV3. See `SwapData.ts` for details.
> Fix UniV3 path in 0x fill data

- src/constants/contracts.ts
- src/tests/dsETH/dsETH.mint.test.ts
- src/tests/dsETH/dsETH.redeem.test.ts
- src/tests/iceth.test.ts
- src/tests/utils/index.ts
- src/tests/wseth2.test.ts
* Adds new address for FlashMintLeveraged contract on mainnet
* Updates and reactivates tests for `icETH` (which had to be temporarily deactivated before)
* Fixes some test related issues
##
Due to Curve changing their calculator quotes, the `FlashMintLeveraged` had to be updated. Since there was a new deployed contract, the address had to be overwritten. This was causing specficially issues with `icETH`
> Add new flash mint leveraged contract (mainnet)

- src/utils/issuanceModules.test.ts
- src/utils/issuanceModules.ts
* Adds tests for all active indices to return correct issuance modules based on index. 
* Restructures test to make processing easier and quicker
> Add missing tests for issuance modules

- .env.default
- .github/workflows/publish.yml
- README.md
- src/constants/contracts.ts
- src/constants/tokens.ts
- src/flashmint/builders/leveraged.test.ts
- src/quote/indexQuoteProvider.test.ts
- src/quote/indexQuoteProvider.ts
- src/quote/leveraged/provider.test.ts
- src/quote/wrapped/index.test.ts
- src/quote/wrapped/index.ts
- src/tests/dsETH/dsETH.mint.test.ts
- src/tests/dsETH/dsETH.redeem.test.ts
- src/tests/icreth.test.ts
- src/tests/mmi.test.ts
- src/tests/utils/index.ts
- src/tests/utils/quoteTokens.ts
- src/utils/0x.test.ts
- src/utils/0x.ts
- src/utils/componentSwapData.test.ts
- src/utils/componentSwapData.ts
- src/utils/contracts.test.ts
- src/utils/contracts.ts
- src/utils/issuanceModules.test.ts
- src/utils/issuanceModules.ts
- src/utils/swapData.test.ts
- src/utils/swapData.ts
* Makes component swap data dynamic (quotes are now fetched from 0x)
* For icSMMT quotes are limited to `UniV3` only
* Adds returning swap data for `BalancerV2` quotes (in prep for icRETH)
> Make component swap data dynamic

- src/quote/indexQuoteProvider.test.ts
- src/quote/leveraged/provider.test.ts
- src/quote/leveraged/provider.ts
- src/quote/wrapped/index.test.ts
- src/tests/eth2xfli/index.test.ts
- src/tests/gtceth/index.test.ts
- src/tests/mmi.test.ts
- src/utils/componentSwapData.test.ts
* Fixes an issue for redeeming ETH2xFLI when call data is empty
* Run `npm run hardhat`
* Run `npm test src/tests/eth2xfli` (in separate console tab)
> Fix issue redeeming ETH2xFLI

- .github/workflows/publish.yml
- package.json
- src/constants/tokens.ts
- src/quote/indexQuoteProvider.ts
- src/tests/btc2x.test.ts
- src/tests/eth2x.test.ts
- src/tests/utils/quoteTokens.ts
- src/utils/contracts.test.ts
- src/utils/contracts.ts
- src/utils/issuanceModules.test.ts
- src/utils/issuanceModules.ts
* Adds support for BTC2X
* Updates git workflow actions to v4
> feat: add btc2x

- .github/workflows/publish.yml
- src/tests/dseth/index.test.ts
- src/utils/issuanceModules.test.ts
- src/utils/issuanceModules.ts
* Updates dsETH and gtcETH to use the newer DebtIssuanceModuleV2 issuance contract: https://etherscan.io/address/0x04b59F9F09750C044D7CfbC177561E409085f0f3#code
> update issuance modules for dseth and gtceth

- .github/workflows/publish.yml
- package.json
- src/constants/tokens.ts
- src/quote/provider/utils.test.ts
- src/quote/provider/utils.ts
- src/tests/rwa.presale.test.ts
- src/tests/utils/quoteTokens.ts
- src/utils/contracts.test.ts
- src/utils/contracts.ts
- src/utils/issuanceModules.test.ts
- src/utils/issuanceModules.ts
* Adds RWA to allow presale with more tokens than wstETH
> feat: add rwa presale

- src/quote/flashmint/hyeth/component-quotes/index.ts
- src/quote/flashmint/hyeth/component-quotes/morpho.ts
- src/tests/btc2x.test.ts
* Adds quote provider for Morpho tokens
> feat: add morpho quote provider

- .github/workflows/publish.yml
- hardhat.arbitrum.config.js
- hardhat.base.config.js
- hardhat.config.js
- package-lock.json
- package.json
- src/tests/hyeth.test.ts
1. Updating hardhat. (My guess is our previous version did support the opcodes added in the cancun hardfork which seem to be used by some pendle contracts)
2. Simulating an increase of the exchangeRateFactor for ezEth to 0.5%. For this to work in prod we will need to execute the corresponding tx on mainnet.
> Fix Failing HyETH Tests

- README.md
- src/quote/provider/icusd.ts
- src/quote/provider/index.ts
- src/quote/provider/utils.test.ts
- src/quote/provider/utils.ts
- src/tests/arbitrum/btc2x.test.ts
- src/tests/arbitrum/btc3x.test.ts
- src/tests/arbitrum/eth2x.test.ts
- src/tests/arbitrum/eth3x.test.ts
- src/tests/arbitrum/ibtc1x.test.ts
- src/tests/arbitrum/ieth1x.test.ts
- src/tests/base/eth2x.test.ts
- src/tests/base/eth3x.test.ts
- src/tests/btc2x.test.ts
- src/tests/dseth/index.test.ts
- src/tests/eth2x.test.ts
- src/tests/gtceth/index.test.ts
- src/tests/hyeth.test.ts
- src/tests/ic21.test.ts
- src/tests/iceth.test.ts
- src/tests/icusd.test.ts
- src/tests/utils/test-factory.ts
* Changes quote request amounts to `string`, so that clients do not have to deal wit BigNumber or BigInt or can choose freely which one to use.
> feat: update quote request amounts to strings

- src/utils/component-swap-data.ts
Some morpho components seem to have a tiny diff in preview amounts during execution. So this PR adds a small slippage (0.01%) to the output of the previewMint/Redeem functions.
> feat: add slippage for preview amounts

- src/utils/clients.ts
- src/utils/component-swap-data.ts
Updates create client to use a RPC URL as argument to be able to pass in the needed transport url (and not rely on an env var).
> fix: create client with url

- .github/workflows/publish.yml
- hardhat.config.js
- src/flashmint/builders/hyeth.test.ts
- src/quote/flashmint/hyeth/provider.test.ts
- src/quote/flashmint/hyeth/provider.ts
- src/quote/flashmint/hyeth/swap-data.ts
- src/quote/provider/index.test.ts
- src/tests/hyeth.test.ts
> fix: hyeth quotes

- src/quote/flashmint/hyeth/component-quotes/index.ts
- src/tests/hyeth.test.ts
- src/utils/component-swap-data.test.ts
Fixes hyETH quotes for ERC20's by temporarily ignoring the WETH dust - which otherwise leads to decimals issues of the quote amount.
> fix: hyeth quotes for erc20's

- src/quote/flashmint/hyeth/component-quotes/morpho.ts
- src/quote/flashmint/leveraged-zeroex/fallback.ts
- src/quote/flashmint/leveraged-zeroex/provider.ts
- src/quote/flashmint/leveraged-zeroex/utils.ts
- src/quote/flashmint/zeroEx/provider.ts
- src/quote/swap/adapters/lifi/index.ts
- src/quote/swap/adapters/zeroex_v2/client.ts
- src/quote/swap/adapters/zeroex_v2/index.ts
- src/quote/swap/adapters/zeroex_v2/utils.ts
- src/quote/swap/interfaces.ts
- src/tests/base/btc2x.test.ts
Fixes quoting by...
* using 0x v2 swap quote provider for `getSellAmount()` because this might not have been picking up the env vars - and so possibly fails due to rate limits
* excluding woofi as a source for Arbitrum and Base (due to failing tx's)
* failing more gracefully in some instances (logging warnings instead of throwing error; should be improved in further PRs)
> fix: quoting

- README.md
- src/quote/flashmint/leveraged-zeroex/provider.ts
Fixes get swap data input/output token result to return null if it can't find a swap quote, just like other functions. This way no wrong quotes should be returned. Better error handling in general will follow in upcoming PRs.
> fix: failing swap quote response

- src/quote/swap/adapters/zeroex_v2/utils.test.ts
- src/quote/swap/adapters/zeroex_v2/utils.ts
Fixes slippage values introducing rounding. Specifically, where floating-point numbers e.g. 1.093097 or as simple as 1.1 could cause issues.
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/EPSILON
> fix: slippage

- src/quote/provider/index.ts
Fixes response `value` in transaction object of static quote provider response. Has to be `BigNumber` (instead of BigInt).
> fix: response value
